name: my_first_app
description: A new Flutter project.
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.16
  url_launcher: ^6.1.14
  flutter_otp_text_field: ^1.1.1
  carousel_slider: ^4.0.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  firebase_storage: ^11.5.0
  cloud_firestore: ^4.13.3
  fluttertoast: ^8.2.3
  firebase_core_web: ^2.8.1
  provider: ^5.0.0
  firebase_database: ^10.3.4
  sqflite: ^2.0.0+3
  path: ^1.8.3
#  flutter_native_splash: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  video_player: ^2.7.2

#flutter_native_splash:
#  color: '#FD8D14'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - asset/images/
    - asset/images/popular_home/
    - asset/images/home_category_img/
    - asset/images/home_page_slider/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
